"""Topics used to select PubMed abstracts for the retrieval corpus.

Covers every DDXPlus pathology (an evaluation set, Phase 6) plus common emergency /
internal-medicine presentations and pharmacology. Each topic becomes a PubMed query
on MeSH major topic or title; articles are taken round-robin across topics so any
corpus size covers all of them. Phrasings were tuned so each query returns results
(e.g. "Long QT Syndrome" rather than "QT prolongation drug-induced").
"""

# The 49 DDXPlus pathologies (named as PubMed would index them).
DDXPLUS = [
    "COPD exacerbation",
    "dystonic reaction",
    "laryngitis",
    "otitis media",
    "pulmonary edema",
    "acute rhinosinusitis",
    "allergic rhinitis",
    "anaphylaxis",
    "anemia",
    "atrial fibrillation",
    "Boerhaave syndrome",
    "bronchiectasis",
    "bronchiolitis",
    "acute bronchitis",
    "asthma exacerbation",
    "Chagas disease",
    "chronic rhinosinusitis",
    "cluster headache",
    "croup",
    "Ebola virus disease",
    "epiglottitis",
    "gastroesophageal reflux disease",
    "Guillain-Barre syndrome",
    "acute HIV infection",
    "influenza",
    "inguinal hernia",
    "laryngospasm",
    "angioedema",
    "myasthenia gravis",
    "myocarditis",
    "supraventricular tachycardia",
    "pancreatic cancer",
    "panic disorder",
    "pericarditis",
    "pneumonia",
    "myocardial infarction",
    "pulmonary embolism",
    "lung cancer",
    "sarcoidosis",
    "scombroid",
    "systemic lupus erythematosus",
    "spontaneous pneumothorax",
    "rib fractures",
    "stable angina",
    "tuberculosis",
    "upper respiratory tract infection",
    "unstable angina",
    "pharyngitis",
    "whooping cough",
]

EMERGENCY_AND_MEDICINE = [
    "acute coronary syndrome",
    "aortic dissection",
    "sepsis",
    "septic shock",
    "meningitis",
    "encephalitis",
    "stroke",
    "transient ischemic attack",
    "subarachnoid hemorrhage",
    "intracerebral hemorrhage",
    "seizures",
    "status epilepticus",
    "syncope",
    "heart failure",
    "cardiac tamponade",
    "hypertensive emergency",
    "deep vein thrombosis",
    "appendicitis",
    "acute cholecystitis",
    "acute pancreatitis",
    "diverticulitis",
    "bowel obstruction",
    "gastrointestinal hemorrhage",
    "peptic ulcer",
    "mesenteric ischemia",
    "diabetic ketoacidosis",
    "hypoglycemia",
    "hyperosmolar hyperglycemic state",
    "acute kidney injury",
    "urinary tract infection",
    "pyelonephritis",
    "kidney stones",
    "cellulitis",
    "necrotizing fasciitis",
    "ectopic pregnancy",
    "preeclampsia",
    "migraine",
    "temporal arteritis",
    "hyperkalemia",
    "hyponatremia",
    "hypercalcemia",
    "thyroid storm",
    "hypothyroidism",
    "adrenal insufficiency",
    "liver cirrhosis",
    "acute liver failure",
    "viral hepatitis",
    "inflammatory bowel disease",
    "celiac disease",
    "gout",
    "septic arthritis",
    "rheumatoid arthritis",
    "dengue",
    "malaria",
    "typhoid fever",
    "leptospirosis",
    "COVID-19",
    "infective endocarditis",
    "delirium",
    "alcohol withdrawal",
    "drug overdose",
    "acetaminophen poisoning",
    "organophosphate poisoning",
    "snake bites",
    "heat stroke",
    "hypothermia",
    "pneumocystis pneumonia",
    "febrile neutropenia",
    "sickle cell crisis",
    "thrombotic thrombocytopenic purpura",
    "heparin-induced thrombocytopenia",
]

PHARMACOLOGY = [
    "drug interactions",
    "adverse drug reactions",
    "anticoagulants",
    "Long QT Syndrome",
    "serotonin syndrome",
    "drug-induced liver injury",
    "antibiotic stewardship",
    "polypharmacy",
    "opioid-induced respiratory depression",
    "rhabdomyolysis",
]

TOPICS: list[str] = DDXPLUS + EMERGENCY_AND_MEDICINE + PHARMACOLOGY
